spring:
  application:
    name: fabrica-chocolate
  datasource:
   url: jdbc:mariadb://localhost:3306/fabrica-chocolate?createDatabaseIfNotExist=true
   username: root
   password: root
   driver-class-name: org.mariadb.jdbc.Driver
   hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
    max-lifetime: 180000
    minimum-idle: 5
    validation-timeout: 3000
    idle-timeout: 10000
  jpa:
   open-in-view: true
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
   properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
      format-sql: true
   show-sql: true   
logging:
  file: 
   name: "c:/logs/fabrica-chocolate/fabrica-chocolate.log"
  level:
    org:
      hibernate:
        type: info
    jdbc: info
    root: info